### ISSUE TITLE
bug: 새로고침 시 테이프  컬러 초기화 및 테이프 날짜 관련 에러 

### ISSUE THREAD

**Issue by Kimkyungmin123** [twentiethcenturygangsta/cassette-client#101]
## Description
ssr로 인한 clinet - server 컬러 값 매치되지 않아서 새로고침시 기본 컬러(cassette orange)가 들어감.
게스트에게 받은 테이프의 날짜가 현재 날짜로 동일하게 찍히 고 있음.

## Todo
 - [x] 새로고침 시 테이프  컬러 초기화 해결 
 - [ ] ~테이프 수정 시 새로고침 막기~
 - [x] 테이프 날짜 현재 날짜가 들어가는 에러  : response data.timestamp에 현재 날짜가 찍힘
