### ISSUE TITLE
feat: 화면 생성

### ISSUE THREAD

**Issue by ddongule** [twentiethcenturygangsta/cassette-client#13]
## Description
- 페이지 조립

## Todo
- [ ] 카세트 만들기 페이지 
- [ ] 목솔리 남기는 닉네임, 제목 페이지
- [ ] 카세트 완성 페이지
- [ ] 카세트 듣는 페이지 

## ETC
기타사항
