### ISSUE TITLE
feat: navbar 기능 연동

### ISSUE THREAD

**Issue by Kimkyungmin123** [twentiethcenturygangsta/cassette-client#34]
## Description
navigation bar 메뉴 기능 연동 시키기

## Todo
- [x] 링크 연결
- [x] 로그아웃 기능 구현
- [x] 탈퇴 api 연동
- [x] navigation bar 여닫기 활성화
