### ISSUE TITLE
fix: 모바일 뷰 깨짐에러 및 기능 에러 수정

### ISSUE THREAD

**Issue by Kimkyungmin123** [twentiethcenturygangsta/cassette-client#71]
## Description
[02.11 회의](https://www.notion.so/12-d0abbdf17a1844ebb1457f3bcce4d83b?p=b80c5bfa5c71499e93e194f2fc07faf3&pm=s) 후 발견된 에러사항, 건의 사항 반영

## Todo
- [x] 링크 복사할 때 토스트 UI가 style 적용 수정하기 (브라우저에서 flex gap 적용 안되는 버그)
- [x] withdrawal page dorp down  화살표 방향  (down -> up)
- [x] 테이프 공유하기 버튼 위치 변경
- [ ] PWA화면 확대 및 축소 안되게 수정
- [ ] PWA 배경색 변경 
- [x] 링크 복사 안되는 버그 해결 ( chrome은 복사가능하지만, motorola에서 카카오톡을 눌러서 웹뷰로 봤을 때 안됨)
- [x] tape component - 테이프 생성 시 날짜 추가
- [x] 녹음 할 때 시간 카운트가 초가 아닌 분이 올라가는 버그 해결
- [x] 404 page 추가
- [x] modify-tape-info page에서  placeholder 값을 → value로 수정
- [x] max width 추가
