### ISSUE TITLE
feat: 전체 트렉병합된 테잎 받아오기, 테이프 다운로드, 트렉  이동 

### ISSUE THREAD

**Issue by Kimkyungmin123** [twentiethcenturygangsta/cassette-client#86]
## Description
12개 트렉이 채워지면 전체 tape를 생성해주는 기능과 각 트렉을 다운로드 하는 기능 구현.
( +부가적인 트렉 플레이 관련 기능 구현)

## Todo
- [x] 전체 테이프 생성
- [x] 개인 테이프의 트렉 다운로드
- [x] 트렉 이동 기능 추가
- [x] 각 트렉 클릭시 오디오 연동

## ETC
현재 `.wav` 파일 병합시 문제가 있어서 해결 된 후 전체 테이프 생성 구현
