### ISSUE TITLE
Blob File Converting

### ISSUE THREAD

**Issue by oereo** [twentiethcenturygangsta/cassette-client#89]
## Description
Blob file type converting and track creation API compatible operation

## Todo
- [x] Blob file type converting
    - [x] Added a module that converts the type of blob file from webm to wave
    - [x] 16-bit audio or 32-bit audio
- [x] API Format
